In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [3]:
arr1 ** arr2

array([  1,  32, 729], dtype=int32)

In [4]:
arr1 +1

array([2, 3, 4])

In [7]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[1,2,3]])
a+b

array([[5, 7, 9],
       [2, 4, 6]])

In [9]:
a = np.array([[1],[2]])
b = np.array([[4,5,6],[1,2,3]])
a+b

array([[5, 6, 7],
       [3, 4, 5]])

In [13]:
import math
math.pi

3.141592653589793

# 행열곱

In [18]:
c = np.arange(1,7).reshape(2,3)
d = np.arange(11,17).reshape(3,2)
np.dot(c,d)

array([[ 82,  88],
       [199, 214]])