In [5]:
# 넘파이 불러오기
import numpy as np

In [2]:
a = np.array(1)
a

array(1)

In [3]:
ndarr_1 = np.array([1,2,3])
print(ndarr_1)

[1 2 3]


In [4]:
ndarr_2 = np.array([1,2.0,3])
print(ndarr_2)

[1. 2. 3.]


In [5]:
# 모두 가장 상위 자료형으로 변환
ndarr_3 = np.array([1,2.0,'3'])
print(ndarr_3)

['1' '2.0' '3']


In [7]:
# 타입확인
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [8]:
print(np.array(1+2j).dtype)
print(np.array(print).dtype)

complex128
object


In [11]:
print(ndarr_1.shape)  # 배열 크기
print(ndarr_1.ndim)   # 배열 차원

(3,)
1


In [13]:
# 2차원
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


In [6]:
# 3차원
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  # ,dtype =float
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)
print(tensor.size)  # 요소 수

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32
12


In [18]:
list(tensor)

[array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[ 7.,  8.,  9.],
        [10., 11., 12.]])]

In [20]:
# 리스트로 변환
list(map(list,list(matrix)))

[[1, 2, 3], [4, 5, 6]]

In [21]:
tensor.tolist()

[[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]]]

shape 다른 리스트 > 넘파이 
변환시 오류 주의

In [22]:
# 세트 {}
{1,1,2,2,3}

{1, 2, 3}

In [25]:
# 넘파이 변환시 리스트화
np.array(list({1,1,2,3,2}))

array([1, 2, 3])

In [31]:
list_ = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(list_[0][1][0])

3


# 배열인덱싱

In [32]:
arr_1=np.array([[1,2],
                [3,4],
                [5,6]])

In [51]:
print('1:' ,arr_1[[0]])
print('2:' ,arr_1[[0,2]])

1: [[1 2]]
2: [[1 2]
 [5 6]]


In [49]:
# [x,y,z],[1,2,3] x의1번째 y의2번째 z의3번째 
print('3:' ,arr_1[[0,1,2],[0,1,0]])
print('3:' ,arr_1[[0,1,2]])
print('3:' ,arr_1[[0,1,0]])

3: [1 4 5]
3: [[1 2]
 [3 4]
 [5 6]]
3: [[1 2]
 [3 4]
 [1 2]]


In [50]:
print('4:' ,arr_1[[0,0],[1,1]])
print('4:' ,arr_1[[0,0]])

4: [2 2]
4: [[1 2]
 [1 2]]


In [52]:
arr_2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [54]:
b=np.array([0,1,2,3])

In [55]:
c=np.array([0,2,0,1])

In [56]:
print(arr_2[b,c])

[ 1  6  7 11]


In [60]:
arr=np.array([1,2,3,4,5])

In [61]:
print(arr[[True,False,True,True,False]])

[1 3 4]


In [62]:
print(arr[arr>=3])

[3 4 5]


In [64]:
score =np.array([[78,91,84,89,93,65],[82,87,96,79,91,73]])
score

array([[78, 91, 84, 89, 93, 65],
       [82, 87, 96, 79, 91, 73]])

In [75]:
print(score[0][score[0]>=90])
print(score[1][score[1]>=90])

[91 93]
[96 91]


# 배열 슬라이싱

In [86]:
matrix_1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
matrix_1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# [행범위, 열범위] x:y => x~y-1

In [77]:
matrix_1[:,0]

array([ 1,  6, 11, 16])

In [78]:
# 2차원 유지
matrix_1[:,:1]

array([[ 1],
       [ 6],
       [11],
       [16]])

In [79]:
matrix_1[1,:]

array([ 6,  7,  8,  9, 10])

In [80]:
matrix_1[1]

array([ 6,  7,  8,  9, 10])

In [87]:
matrix_1[1:2,:]

array([[ 6,  7,  8,  9, 10]])

In [89]:
# 1,3 행  2~끝 열
matrix_1[[1,3],2:]

array([[ 8,  9, 10],
       [18, 19, 20]])

In [7]:
tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
# [x,,], [y,,], [z,,]  => [[x][y][z],,]
tensor[[1,0,0],[1,0,1],[0,1,2]]

array([10,  2,  6])

In [14]:
tensor[0,:,:2]

array([[1, 2],
       [4, 5]])

In [18]:
# [rank, 행,열]
tensor[1,:,2]

array([ 9, 12])

In [ ]:
# [x:y,[1,3,5]]

# Reshape , shape 변형

In [ ]:
array.reshape(shape)

In [21]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [23]:
arr.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [24]:
arr.reshape(1,1,6)

array([[[1, 2, 3, 4, 5, 6]]])

In [25]:
arr.reshape(2,1,3)

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [26]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [27]:
# 자동 -1
arr.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
arr.reshape(arr.size//2,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
tensor = np.array(range(1,37))
tensor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [32]:
tensor.reshape(3,3,-1)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [33]:
tensor.reshape(-1,9)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36]])

# Flatten 1줄 나열

In [34]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

# Arange 

In [35]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [41]:
np.arange(0,5,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [42]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
np.arange(100,191,10).reshape(2,5)

array([[100, 110, 120, 130, 140],
       [150, 160, 170, 180, 190]])

In [64]:
arr3= np.arange(-2,2.1,0.5).reshape(3,3,-1)
arr3

array([[[-2. ],
        [-1.5],
        [-1. ]],

       [[-0.5],
        [ 0. ],
        [ 0.5]],

       [[ 1. ],
        [ 1.5],
        [ 2. ]]])

# zeros, ones, empty, _like, identity, eye, full

In [62]:
# (shape,dtype)
print(np.zeros((2,3),int))
print(np.ones((2,3)))

# 빈값 이지만 메모리에 저장된 값 저장 될 수 있
print(np.empty((2,3),np.int8))  

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]]


In [65]:
# 원하는 배열과 같은 크기
np.zeros_like(arr3)

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

In [67]:
# 단위행열
# (size,dtype)
np.identity(5,int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [68]:
# 단위행열 1대각선 위치 지정
# M= 보여지는 열 개수, k= 대각선 위치 이동
np.eye(5,k=1,M=7)

array([[0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])

In [69]:
np.full((2,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

# Random

In [70]:
# 0~5 중 정수 랜덤 
np.random.randint(6)

1

In [78]:
# 1~ 5,3,9
np.random.randint(1,[5,3,9])

array([4, 2, 4])

In [72]:
# 0~1 표준정규분포
np.random.rand(5,2)

array([[0.29302353, 0.57187655],
       [0.16545846, 0.59791664],
       [0.50758427, 0.37040704],
       [0.11119138, 0.55719274],
       [0.56516222, 0.42141992]])

In [74]:
# 평균0 , 표준편차1 
np.random.randn(5,2)

array([[-0.7309397 ,  0.03389881],
       [-1.03194254,  0.17833245],
       [-1.50597697, -1.24415888],
       [-1.51224267,  0.38531479],
       [ 0.63239207, -0.16375095]])

# 연산함수
sum mean:평균 max min log sqrt std:표준편차 exp:지수 sin,cos,tan abs/fabs:절대값 

ceil:올림 floor:버림 roound:반올림 mod:% 
add subtract:- multiply:* divide:나누기 power:제곱

In [84]:
arr2 = np.random.randn(3,5)
arr2

array([[ 0.34808453,  0.54208829, -0.01666847, -0.38173501,  0.74434888],
       [-0.122861  , -0.21305045, -0.0399612 , -2.17964778, -1.88173758],
       [-0.58076595, -1.18517282, -0.3524607 ,  1.36152681,  0.94264549]])

In [85]:
sum(arr2)
arr2.sum()

-3.015366953174708

In [86]:
# 같은 행 같은 자리 합
arr2.sum(axis=0)

array([-0.35554241, -0.85613498, -0.40909037, -1.19985598, -0.19474321])

In [87]:
# 같은 열 같은 자리 합
arr2.sum(axis=1)

array([ 1.23611822, -4.43725801,  0.18577284])

# Sort

In [88]:
# 열 기준
np.sort(arr2)

array([[-0.38173501, -0.01666847,  0.34808453,  0.54208829,  0.74434888],
       [-2.17964778, -1.88173758, -0.21305045, -0.122861  , -0.0399612 ],
       [-1.18517282, -0.58076595, -0.3524607 ,  0.94264549,  1.36152681]])

In [89]:
# 내림차순
np.sort(arr2)[::-1]

array([[-1.18517282, -0.58076595, -0.3524607 ,  0.94264549,  1.36152681],
       [-2.17964778, -1.88173758, -0.21305045, -0.122861  , -0.0399612 ],
       [-0.38173501, -0.01666847,  0.34808453,  0.54208829,  0.74434888]])

In [91]:
[np.random.randint(1,101) for n in range(5)]

[53, 63, 12, 59, 64]

# 배열 합치기
Vstack:수직합 Hstack:수평합 concatenate:수직수평합

In [106]:
v1= np.array([1,2,3]).reshape(3,1)
v2= np.array([4,5,6]).reshape(3,1)
np.vstack([v1,v2])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [107]:
np.hstack([v1,v2])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [108]:
# 같은 차원
# x,y,z 축 0,1,2
np.concatenate([v1,v2],axis=0)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [119]:
mat=np.array([[1,2,3],[4,5,6]])
vec= np.array([7,8,9])
np.vstack([mat,vec])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
# concatenate 사용시 reshape
vec.reshape(1,3)
#np.concatenate([mat,vec],axis=1)

array([[7, 8, 9]])

# 행/열 변환 transpose

In [129]:
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
mat.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [132]:
mat.T

array([[1, 4],
       [2, 5],
       [3, 6]])

# argmax, argmin
flat 했을때 최댓값 위치

In [146]:
arr2

array([[ 0.34808453,  0.54208829, -0.01666847, -0.38173501,  0.74434888],
       [-0.122861  , -0.21305045, -0.0399612 , -2.17964778, -1.88173758],
       [-0.58076595, -1.18517282, -0.3524607 ,  1.36152681,  0.94264549]])

In [137]:
# 각 행별 최댓값
np.argmax(arr2,0)

array([0, 0, 0, 2, 2], dtype=int64)

# fancy index 
b=[3,4]
a[b] a의 3,4번자리

In [142]:
arr1 = np.random.randn(20)
arr1

array([-1.0066108 , -0.48796733, -0.47612366, -0.49932139, -2.08600699,
       -0.92833192,  0.86310413, -0.43198061, -0.47459901, -0.41406505,
       -0.06443681, -1.02948072,  0.71118238,  0.2996093 ,  1.19648006,
       -1.55436349,  0.23593908, -0.44864996, -0.02856479,  0.91379507])

In [143]:
arr1[np.argmax(arr1)]

1.1964800582958706

In [150]:
np.max(arr1)

1.1964800582958706