In [1]:
import numpy as np

In [4]:
n = np.random.randn(3,5)
n

array([[ 0.93261019,  0.89475139, -2.30567945,  0.51338072,  0.96632423],
       [-0.20730973,  0.80692448,  1.45668306,  0.66857447,  0.80141575],
       [-0.4828191 , -1.11661027, -0.12212261, -0.06092184,  0.56715903]])

In [ ]:
# 파이썬 경로는 / 구분

# 저장

In [5]:
# 'C:/Users/Admin/code/WebApp/Python'
filepath = './n.npy'
n.tofile(filepath)

# 불러오기

In [7]:
m= np.fromfile('n.npy')
print(m)

[ 0.93261019  0.89475139 -2.30567945  0.51338072  0.96632423 -0.20730973
  0.80692448  1.45668306  0.66857447  0.80141575 -0.4828191  -1.11661027
 -0.12212261 -0.06092184  0.56715903]


In [ ]:
# shape 바꿔서 나옴

# np.save, np.load
shape 유지
file 과 연동시 오류 생김

In [8]:
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[ 0.93261019  0.89475139 -2.30567945  0.51338072  0.96632423]
 [-0.20730973  0.80692448  1.45668306  0.66857447  0.80141575]
 [-0.4828191  -1.11661027 -0.12212261 -0.06092184  0.56715903]]


# 텍스트 저장
csv 가능

In [9]:
np.savetxt('n1.txt',n)

In [12]:
m1 = np.loadtxt('n1.txt')
m1

array([[ 0.93261019,  0.89475139, -2.30567945,  0.51338072,  0.96632423],
       [-0.20730973,  0.80692448,  1.45668306,  0.66857447,  0.80141575],
       [-0.4828191 , -1.11661027, -0.12212261, -0.06092184,  0.56715903]])

In [15]:
# delimiter 구분 가능하게
np.savetxt('n1.csv',n,delimiter=',')
# 불러올땐 ,dtype=str 가능

In [17]:
np.savetxt('data.csv',np.arange(1,26,).reshape(5,5),delimiter=',')

In [18]:
arr1=np.loadtxt('data.csv',dtype=str)
arr1

array(['1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00,5.000000000000000000e+00',
       '6.000000000000000000e+00,7.000000000000000000e+00,8.000000000000000000e+00,9.000000000000000000e+00,1.000000000000000000e+01',
       '1.100000000000000000e+01,1.200000000000000000e+01,1.300000000000000000e+01,1.400000000000000000e+01,1.500000000000000000e+01',
       '1.600000000000000000e+01,1.700000000000000000e+01,1.800000000000000000e+01,1.900000000000000000e+01,2.000000000000000000e+01',
       '2.100000000000000000e+01,2.200000000000000000e+01,2.300000000000000000e+01,2.400000000000000000e+01,2.500000000000000000e+01'],
      dtype='<U124')

In [ ]:
# 중복 지역 확인
np.unique

In [7]:
data = np.loadtxt('ex1_지역별전기요금.csv',delimiter=',',dtype=np.int32)
print(data[:5,:])

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


In [23]:
data

array([[      1,  565082,     273,   27177],
       [      2, 2827233,     444,   45111],
       [      3, 1144913,     289,   29043],
       [      4, 1131034,     230,   22436],
       [      5,  380425,     391,   38020],
       [      6,  668623,     364,   35245],
       [      7,  425659,     344,   32331],
       [      8,  947300,     366,   36274],
       [      9, 2737725,     361,   36569],
       [     10,   49394,     580,   57091],
       [     11,  323151,     353,   35470],
       [     12,  734723,     398,   40049],
       [     13,  726699,     249,   25120],
       [     14,  634696,     285,   28556],
       [     15,  258605,     221,   22180],
       [     16,  742285,     282,   27901],
       [     17,  584500,     268,   26899]])

In [8]:
data.shape

(17, 4)

In [16]:
len(np.unique(data[:,0]))

17

In [17]:
# 작은 순서를 자리번호로 표시
np.argsort([1,2,6,3,0,0,10])

array([4, 5, 0, 1, 3, 2, 6], dtype=int64)

In [22]:
data_1 = np.argsort(data[:,1])
data_1

array([ 9, 14, 10,  4,  6,  0, 16, 13,  5, 12, 11, 15,  7,  3,  2,  8,  1],
      dtype=int64)

In [21]:
data[data_1]

array([[     10,   49394,     580,   57091],
       [     15,  258605,     221,   22180],
       [     11,  323151,     353,   35470],
       [      5,  380425,     391,   38020],
       [      7,  425659,     344,   32331],
       [      1,  565082,     273,   27177],
       [     17,  584500,     268,   26899],
       [     14,  634696,     285,   28556],
       [      6,  668623,     364,   35245],
       [     13,  726699,     249,   25120],
       [     12,  734723,     398,   40049],
       [     16,  742285,     282,   27901],
       [      8,  947300,     366,   36274],
       [      4, 1131034,     230,   22436],
       [      3, 1144913,     289,   29043],
       [      9, 2737725,     361,   36569],
       [      2, 2827233,     444,   45111]])

In [24]:
# 내림차순
np.sort(data[:,:])[::-1]

array([[     17,     268,   26899,  584500],
       [     16,     282,   27901,  742285],
       [     15,     221,   22180,  258605],
       [     14,     285,   28556,  634696],
       [     13,     249,   25120,  726699],
       [     12,     398,   40049,  734723],
       [     11,     353,   35470,  323151],
       [     10,     580,   49394,   57091],
       [      9,     361,   36569, 2737725],
       [      8,     366,   36274,  947300],
       [      7,     344,   32331,  425659],
       [      6,     364,   35245,  668623],
       [      5,     391,   38020,  380425],
       [      4,     230,   22436, 1131034],
       [      3,     289,   29043, 1144913],
       [      2,     444,   45111, 2827233],
       [      1,     273,   27177,  565082]])

In [25]:
data_2 = np.argsort(data[:,1])[::-1]
data_2

array([ 1,  8,  2,  3,  7, 15, 11, 12,  5, 13, 16,  0,  6,  4, 10, 14,  9],
      dtype=int64)

In [26]:
np.sum(data[:,1])

14882047

In [33]:
print(data[:,2].mean())
print(round(data[:,2].mean(),2))

335.1764705882353
335.18


In [37]:
a = data[:,2] > data[:,2].mean()
data[a]

array([[      2, 2827233,     444,   45111],
       [      5,  380425,     391,   38020],
       [      6,  668623,     364,   35245],
       [      7,  425659,     344,   32331],
       [      8,  947300,     366,   36274],
       [      9, 2737725,     361,   36569],
       [     10,   49394,     580,   57091],
       [     11,  323151,     353,   35470],
       [     12,  734723,     398,   40049]])

In [60]:
data2=np.loadtxt('ex2_전년대비_시도별_교통사망사고.csv',delimiter=',')
data2

array([[ 2.014e+03,  1.000e+00,  2.180e+02,  4.800e+00, -9.000e+00,
        -4.000e+00],
       [ 2.014e+03,  2.000e+00,  8.720e+02,  1.900e+01, -4.500e+01,
        -4.900e+00],
       [ 2.014e+03,  3.000e+00,  4.010e+02,  8.700e+00, -4.500e+01,
        -1.010e+01],
       [ 2.014e+03,  4.000e+00,  4.640e+02,  1.010e+01, -4.100e+01,
        -8.100e+00],
       [ 2.014e+03,  5.000e+00,  9.900e+01,  2.200e+00, -5.000e+00,
        -4.800e+00],
       [ 2.014e+03,  6.000e+00,  1.820e+02,  4.000e+00,  1.900e+01,
         1.170e+01],
       [ 2.014e+03,  7.000e+00,  9.900e+01,  2.200e+00,  8.000e+00,
         8.800e+00],
       [ 2.014e+03,  8.000e+00,  1.630e+02,  3.600e+00, -4.700e+01,
        -2.240e+01],
       [ 2.014e+03,  9.000e+00,  3.860e+02,  8.400e+00,  1.400e+01,
         3.800e+00],
       [ 2.014e+03,  1.000e+01,  2.000e+01,  4.000e-01,  0.000e+00,
         0.000e+00],
       [ 2.014e+03,  1.100e+01,  1.030e+02,  2.200e+00, -1.600e+01,
        -1.340e+01],
       [ 2.014e+03,  

In [63]:
data2[data2[:,1] ==4]

array([[2014. ,    4. ,  464. ,   10.1,  -41. ,   -8.1]])

In [73]:
data2[:,2].sum()

4583.0

In [71]:
data2[:,2].mean()

269.5882352941176

In [75]:
data2[data2[:,4] == max(data2[:,4])]

array([[2014. ,    6. ,  182. ,    4. ,   19. ,   11.7]])

In [77]:
data2[np.argmax(data2[:,4])]

array([2014. ,    6. ,  182. ,    4. ,   19. ,   11.7])

In [87]:
data2[(data2[:,2]>400)][:,[2,4,5]]

array([[872. , -45. ,  -4.9],
       [401. , -45. , -10.1],
       [464. , -41. ,  -8.1]])